DROP SEQUENCE EXNOSEQ;
DROP TABLE EXBOARD;

CREATE SEQUENCE EXNOSEQ;
CREATE TABLE EXBOARD(
	EXNO NUMBER PRIMARY KEY,
	EXNAME VARCHAR2(1000) NOT NULL,
	EXTITLE VARCHAR2(2000) NOT NULL,
	EXCONTENT VARCHAR2(4000) NOT NULL,
	EXDATE DATE NOT NULL
);

INSERT INTO EXBOARD
VALUES(EXNOSEQ.NEXTVAL, 'TEST이름','TEST 제목', 'TEST 내용', SYSDATE);

SELECT * FROM EXBOARD;